// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2IEvhB7IMx0m5s6yG1NUPVoilJ8Rodxw',
    appId: '1:785080321235:web:147d97d461f1bf21528026',
    messagingSenderId: '785080321235',
    projectId: 'tutorapp-36170',
    authDomain: 'tutorapp-36170.firebaseapp.com',
    storageBucket: 'tutorapp-36170.firebasestorage.app',
    measurementId: 'G-D8FY40X3KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW6QeizgRWeeapOrVV1dwLo_67o1qFOpY',
    appId: '1:785080321235:android:679aa515fafd3725528026',
    messagingSenderId: '785080321235',
    projectId: 'tutorapp-36170',
    storageBucket: 'tutorapp-36170.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OQQVFaWMx8nGQdxpkzdb0q3qEsm_jdU',
    appId: '1:785080321235:ios:9916f6a34daab022528026',
    messagingSenderId: '785080321235',
    projectId: 'tutorapp-36170',
    storageBucket: 'tutorapp-36170.firebasestorage.app',
    iosBundleId: 'com.example.tutorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6OQQVFaWMx8nGQdxpkzdb0q3qEsm_jdU',
    appId: '1:785080321235:ios:9916f6a34daab022528026',
    messagingSenderId: '785080321235',
    projectId: 'tutorapp-36170',
    storageBucket: 'tutorapp-36170.firebasestorage.app',
    iosBundleId: 'com.example.tutorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2IEvhB7IMx0m5s6yG1NUPVoilJ8Rodxw',
    appId: '1:785080321235:web:5c8e39a9b478b0f1528026',
    messagingSenderId: '785080321235',
    projectId: 'tutorapp-36170',
    authDomain: 'tutorapp-36170.firebaseapp.com',
    storageBucket: 'tutorapp-36170.firebasestorage.app',
    measurementId: 'G-KDWR6TJT74',
  );
}
